BEGIN TRANSACTION;

CREATE TABLE menu (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	menu_name TEXT NOT NULL UNIQUE,
	description TEXT NOT NULL,
    price TEXT NOT NULL,
    diet_rest_id INTEGER NOT NULL UNIQUE,
    category_id INTEGER NOT NULL UNIQUE
);

-- Sessions Table
CREATE TABLE `categories` (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	category TEXT NOT NULL UNIQUE,
);

CREATE TABLE restriction (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	diet_rest TEXT NOT NULL UNIQUE,

);

CREATE TABLE images (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	img_name TEXT NOT NULL UNIQUE,
	img_ext TEXT NOT NULL,
    menu_id INTEGER NOT NULL UNIQUE,
    img_source TEXT NOT NULL,
    review_id INTEGER NOT NULL UNIQUE
);

CREATE TABLE reviews (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	reviewer TEXT NOT NULL,
	rating TEXT,
    comment TEXT NOT NULL
);

-- INSERT INTO `menu_images` ()
-- VALUES(1, '', 1);

COMMIT;
